services:
  - type: web
    name: discord-competitive-ia
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DISCORD_PUBLIC_KEY
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_APP_ID
        sync: false
